### PR TITLE
Feature: Hello_Microverse

### PR DESCRIPTION
**Pull request by yonas44**
Added Linters
Added Html file
Styled the heading
Updated readme file

Thank you for reviewing my PR.

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @yonas44   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [x] Kindly make sure to add a good PR title and PR description. It makes your repo looks more professional. :wink: 

   - Example of good PR
image
  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to write your commit message in imperative tense and capitalized it. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yonas44** [comment]
Hello @levy002 thank you for reviewing my PR I tried to fix the issues as you mentioned but i had one problem, I had a slight problem on myside and I opened a new PR, so is it okay to send the link for the new PR?

**Comment by levy002** [comment]
Hello, @yonas44. There is no need to create a new PR. You can always edit your PR description. Please check the following example:
[Screencast from 20.09.2022 18:02:09.webm](https://user-images.githubusercontent.com/87197412/191308922-9598e27e-1816-483c-a68c-08417e4e9bde.webm)
After editing your PR you can submit the same link.

**Comment by yonas44** [comment]
Thank you for for replying @levy002. But unfortunately I removed the first PR can I send a new one? is that okay?

**Comment by levy002** [comment]
You can always restore your PR even if is deleted. You will see the `restore branch` button. Click on it and continue your work normally. If your project is approved merge it into the main branch.

**Comment by yonas44** [comment]
Okay but i removed the first branch and added a new branch with a new PR, and i can't seem to find the "restore branch". What can i do now? Really sorry for bothering with all this question!

**Comment by yonas44** [comment]
Okay nevermind Mr @levy002 i have reopened the PR. THANK YOU VERY MUCH! for the help!

**Comment by levy002** [comment]
Okay, @yonas44 Have a good time!

**Review by ghost — APPROVED** [review]
Hi @yonas44 , 

Good work implementing the changes requested. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


YesYouAreGIF (2)

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Descriptive PR 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yonas44** [comment]
Okay thank you @frank1738 I will do that right now! And thank you @levy002 once again! Good day to you all!

**Pull request merged**
